'use client';

import { vars } from 'nativewind';

import colors from '@app/constants/colors.constants';

export const config = {
  light: vars({
    '--color-primary-0': colors.light.primary[0],
    '--color-primary-50': colors.light.primary[50],
    '--color-primary-100': colors.light.primary[100],
    '--color-primary-200': colors.light.primary[200],
    '--color-primary-300': colors.light.primary[300],
    '--color-primary-400': colors.light.primary[400],
    '--color-primary-500': colors.light.primary[500],
    '--color-primary-600': colors.light.primary[600],
    '--color-primary-700': colors.light.primary[700],
    '--color-primary-800': colors.light.primary[800],
    '--color-primary-900': colors.light.primary[900],
    '--color-primary-950': colors.light.primary[950],

    '--color-secondary-0': colors.light.secondary[0],
    '--color-secondary-50': colors.light.secondary[50],
    '--color-secondary-100': colors.light.secondary[100],
    '--color-secondary-200': colors.light.secondary[200],
    '--color-secondary-300': colors.light.secondary[300],
    '--color-secondary-400': colors.light.secondary[400],
    '--color-secondary-500': colors.light.secondary[500],
    '--color-secondary-600': colors.light.secondary[600],
    '--color-secondary-700': colors.light.secondary[700],
    '--color-secondary-800': colors.light.secondary[800],
    '--color-secondary-900': colors.light.secondary[900],
    '--color-secondary-950': colors.light.secondary[950],

    '--color-tertiary-0': colors.light.tertiary[0],
    '--color-tertiary-50': colors.light.tertiary[50],
    '--color-tertiary-100': colors.light.tertiary[100],
    '--color-tertiary-200': colors.light.tertiary[200],
    '--color-tertiary-300': colors.light.tertiary[300],
    '--color-tertiary-400': colors.light.tertiary[400],
    '--color-tertiary-500': colors.light.tertiary[500],
    '--color-tertiary-600': colors.light.tertiary[600],
    '--color-tertiary-700': colors.light.tertiary[700],
    '--color-tertiary-800': colors.light.tertiary[800],
    '--color-tertiary-900': colors.light.tertiary[900],
    '--color-tertiary-950': colors.light.tertiary[950],

    '--color-error-0': colors.light.error[0],
    '--color-error-50': colors.light.error[50],
    '--color-error-100': colors.light.error[100],
    '--color-error-200': colors.light.error[200],
    '--color-error-300': colors.light.error[300],
    '--color-error-400': colors.light.error[400],
    '--color-error-500': colors.light.error[500],
    '--color-error-600': colors.light.error[600],
    '--color-error-700': colors.light.error[700],
    '--color-error-800': colors.light.error[800],
    '--color-error-900': colors.light.error[900],
    '--color-error-950': colors.light.error[950],

    '--color-success-0': colors.light.success[0],
    '--color-success-50': colors.light.success[50],
    '--color-success-100': colors.light.success[100],
    '--color-success-200': colors.light.success[200],
    '--color-success-300': colors.light.success[300],
    '--color-success-400': colors.light.success[400],
    '--color-success-500': colors.light.success[500],
    '--color-success-600': colors.light.success[600],
    '--color-success-700': colors.light.success[700],
    '--color-success-800': colors.light.success[800],
    '--color-success-900': colors.light.success[900],
    '--color-success-950': colors.light.success[950],

    '--color-warning-0': colors.light.warning[0],
    '--color-warning-50': colors.light.warning[50],
    '--color-warning-100': colors.light.warning[100],
    '--color-warning-200': colors.light.warning[200],
    '--color-warning-300': colors.light.warning[300],
    '--color-warning-400': colors.light.warning[400],
    '--color-warning-500': colors.light.warning[500],
    '--color-warning-600': colors.light.warning[600],
    '--color-warning-700': colors.light.warning[700],
    '--color-warning-800': colors.light.warning[800],
    '--color-warning-900': colors.light.warning[900],
    '--color-warning-950': colors.light.warning[950],

    '--color-info-0': colors.light.info[0],
    '--color-info-50': colors.light.info[50],
    '--color-info-100': colors.light.info[100],
    '--color-info-200': colors.light.info[200],
    '--color-info-300': colors.light.info[300],
    '--color-info-400': colors.light.info[400],
    '--color-info-500': colors.light.info[500],
    '--color-info-600': colors.light.info[600],
    '--color-info-700': colors.light.info[700],
    '--color-info-800': colors.light.info[800],
    '--color-info-900': colors.light.info[900],
    '--color-info-950': colors.light.info[950],

    '--color-typography-0': colors.light.typography[0],
    '--color-typography-50': colors.light.typography[50],
    '--color-typography-100': colors.light.typography[100],
    '--color-typography-200': colors.light.typography[200],
    '--color-typography-300': colors.light.typography[300],
    '--color-typography-400': colors.light.typography[400],
    '--color-typography-500': colors.light.typography[500],
    '--color-typography-600': colors.light.typography[600],
    '--color-typography-700': colors.light.typography[700],
    '--color-typography-800': colors.light.typography[800],
    '--color-typography-900': colors.light.typography[900],
    '--color-typography-950': colors.light.typography[950],

    '--color-outline-0': colors.light.outline[0],
    '--color-outline-50': colors.light.outline[50],
    '--color-outline-100': colors.light.outline[100],
    '--color-outline-200': colors.light.outline[200],
    '--color-outline-300': colors.light.outline[300],
    '--color-outline-400': colors.light.outline[400],
    '--color-outline-500': colors.light.outline[500],
    '--color-outline-600': colors.light.outline[600],
    '--color-outline-700': colors.light.outline[700],
    '--color-outline-800': colors.light.outline[800],
    '--color-outline-900': colors.light.outline[900],
    '--color-outline-950': colors.light.outline[950],

    '--color-background-0': colors.light.background[0],
    '--color-background-50': colors.light.background[50],
    '--color-background-100': colors.light.background[100],
    '--color-background-200': colors.light.background[200],
    '--color-background-300': colors.light.background[300],
    '--color-background-400': colors.light.background[400],
    '--color-background-500': colors.light.background[500],
    '--color-background-600': colors.light.background[600],
    '--color-background-700': colors.light.background[700],
    '--color-background-800': colors.light.background[800],
    '--color-background-900': colors.light.background[900],
    '--color-background-950': colors.light.background[950],

    '--color-background-error': colors.light.backgroundSpecial.error,
    '--color-background-warning': colors.light.backgroundSpecial.warning,
    '--color-background-success': colors.light.backgroundSpecial.success,
    '--color-background-muted': colors.light.backgroundSpecial.muted,
    '--color-background-info': colors.light.backgroundSpecial.info,

    '--color-indicator-primary': colors.light.indicator.primary,
    '--color-indicator-info': colors.light.indicator.info,
    '--color-indicator-error': colors.light.indicator.error,
  }),
  dark: vars({
    '--color-primary-0': colors.dark.primary[0],
    '--color-primary-50': colors.dark.primary[50],
    '--color-primary-100': colors.dark.primary[100],
    '--color-primary-200': colors.dark.primary[200],
    '--color-primary-300': colors.dark.primary[300],
    '--color-primary-400': colors.dark.primary[400],
    '--color-primary-500': colors.dark.primary[500],
    '--color-primary-600': colors.dark.primary[600],
    '--color-primary-700': colors.dark.primary[700],
    '--color-primary-800': colors.dark.primary[800],
    '--color-primary-900': colors.dark.primary[900],
    '--color-primary-950': colors.dark.primary[950],

    '--color-secondary-0': colors.dark.secondary[0],
    '--color-secondary-50': colors.dark.secondary[50],
    '--color-secondary-100': colors.dark.secondary[100],
    '--color-secondary-200': colors.dark.secondary[200],
    '--color-secondary-300': colors.dark.secondary[300],
    '--color-secondary-400': colors.dark.secondary[400],
    '--color-secondary-500': colors.dark.secondary[500],
    '--color-secondary-600': colors.dark.secondary[600],
    '--color-secondary-700': colors.dark.secondary[700],
    '--color-secondary-800': colors.dark.secondary[800],
    '--color-secondary-900': colors.dark.secondary[900],
    '--color-secondary-950': colors.dark.secondary[950],

    '--color-tertiary-0': colors.dark.tertiary[0],
    '--color-tertiary-50': colors.dark.tertiary[50],
    '--color-tertiary-100': colors.dark.tertiary[100],
    '--color-tertiary-200': colors.dark.tertiary[200],
    '--color-tertiary-300': colors.dark.tertiary[300],
    '--color-tertiary-400': colors.dark.tertiary[400],
    '--color-tertiary-500': colors.dark.tertiary[500],
    '--color-tertiary-600': colors.dark.tertiary[600],
    '--color-tertiary-700': colors.dark.tertiary[700],
    '--color-tertiary-800': colors.dark.tertiary[800],
    '--color-tertiary-900': colors.dark.tertiary[900],
    '--color-tertiary-950': colors.dark.tertiary[950],

    '--color-error-0': colors.dark.error[0],
    '--color-error-50': colors.dark.error[50],
    '--color-error-100': colors.dark.error[100],
    '--color-error-200': colors.dark.error[200],
    '--color-error-300': colors.dark.error[300],
    '--color-error-400': colors.dark.error[400],
    '--color-error-500': colors.dark.error[500],
    '--color-error-600': colors.dark.error[600],
    '--color-error-700': colors.dark.error[700],
    '--color-error-800': colors.dark.error[800],
    '--color-error-900': colors.dark.error[900],
    '--color-error-950': colors.dark.error[950],

    '--color-success-0': colors.dark.success[0],
    '--color-success-50': colors.dark.success[50],
    '--color-success-100': colors.dark.success[100],
    '--color-success-200': colors.dark.success[200],
    '--color-success-300': colors.dark.success[300],
    '--color-success-400': colors.dark.success[400],
    '--color-success-500': colors.dark.success[500],
    '--color-success-600': colors.dark.success[600],
    '--color-success-700': colors.dark.success[700],
    '--color-success-800': colors.dark.success[800],
    '--color-success-900': colors.dark.success[900],
    '--color-success-950': colors.dark.success[950],

    '--color-warning-0': colors.dark.warning[0],
    '--color-warning-50': colors.dark.warning[50],
    '--color-warning-100': colors.dark.warning[100],
    '--color-warning-200': colors.dark.warning[200],
    '--color-warning-300': colors.dark.warning[300],
    '--color-warning-400': colors.dark.warning[400],
    '--color-warning-500': colors.dark.warning[500],
    '--color-warning-600': colors.dark.warning[600],
    '--color-warning-700': colors.dark.warning[700],
    '--color-warning-800': colors.dark.warning[800],
    '--color-warning-900': colors.dark.warning[900],
    '--color-warning-950': colors.dark.warning[950],

    '--color-info-0': colors.dark.info[0],
    '--color-info-50': colors.dark.info[50],
    '--color-info-100': colors.dark.info[100],
    '--color-info-200': colors.dark.info[200],
    '--color-info-300': colors.dark.info[300],
    '--color-info-400': colors.dark.info[400],
    '--color-info-500': colors.dark.info[500],
    '--color-info-600': colors.dark.info[600],
    '--color-info-700': colors.dark.info[700],
    '--color-info-800': colors.dark.info[800],
    '--color-info-900': colors.dark.info[900],
    '--color-info-950': colors.dark.info[950],

    '--color-typography-0': colors.dark.typography[0],
    '--color-typography-50': colors.dark.typography[50],
    '--color-typography-100': colors.dark.typography[100],
    '--color-typography-200': colors.dark.typography[200],
    '--color-typography-300': colors.dark.typography[300],
    '--color-typography-400': colors.dark.typography[400],
    '--color-typography-500': colors.dark.typography[500],
    '--color-typography-600': colors.dark.typography[600],
    '--color-typography-700': colors.dark.typography[700],
    '--color-typography-800': colors.dark.typography[800],
    '--color-typography-900': colors.dark.typography[900],
    '--color-typography-950': colors.dark.typography[950],

    '--color-outline-0': colors.dark.outline[0],
    '--color-outline-50': colors.dark.outline[50],
    '--color-outline-100': colors.dark.outline[100],
    '--color-outline-200': colors.dark.outline[200],
    '--color-outline-300': colors.dark.outline[300],
    '--color-outline-400': colors.dark.outline[400],
    '--color-outline-500': colors.dark.outline[500],
    '--color-outline-600': colors.dark.outline[600],
    '--color-outline-700': colors.dark.outline[700],
    '--color-outline-800': colors.dark.outline[800],
    '--color-outline-900': colors.dark.outline[900],
    '--color-outline-950': colors.dark.outline[950],

    '--color-background-0': colors.dark.background[0],
    '--color-background-50': colors.dark.background[50],
    '--color-background-100': colors.dark.background[100],
    '--color-background-200': colors.dark.background[200],
    '--color-background-300': colors.dark.background[300],
    '--color-background-400': colors.dark.background[400],
    '--color-background-500': colors.dark.background[500],
    '--color-background-600': colors.dark.background[600],
    '--color-background-700': colors.dark.background[700],
    '--color-background-800': colors.dark.background[800],
    '--color-background-900': colors.dark.background[900],
    '--color-background-950': colors.dark.background[950],

    '--color-background-error': colors.dark.backgroundSpecial.error,
    '--color-background-warning': colors.dark.backgroundSpecial.warning,
    '--color-background-success': colors.dark.backgroundSpecial.success,
    '--color-background-muted': colors.dark.backgroundSpecial.muted,
    '--color-background-info': colors.dark.backgroundSpecial.info,

    '--color-indicator-primary': colors.dark.indicator.primary,
    '--color-indicator-info': colors.dark.indicator.info,
    '--color-indicator-error': colors.dark.indicator.error,
  }),
};
